### ISSUE TITLE
Add a hometown file for zsigmon36

### ISSUE THREAD

**Issue by zsigmon36** [githubteacher/feb-developers#77]
## Hometown file

**Tasks**
- [ ] Create a branch
- [ ] Add file
- [ ] Make some commits
- [ ] Open a pull request
- [ ] Have a discussion
- [ ] Merge Pull Request
